# Permalinks
permalink: "/:year-:month-:day/:title"

# Time Zone
timezone: "Europe/Samara"

# Catalogs
include:
  - "_pages"

# Parsers
highlighter: rouge
markdown: kramdown

# Markdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# SASS/SCSS
sass:
  sass_dir: "_scss"
  style: ":compressed"

# Compress HTML
compress_html:
  blanklines: false
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: []
  profile: false
  startings: []

# Website address
url: "http://valentineus.link"
baseurl: ""

# Site description
description: "Free developer and dreamer"
title: "Personal blog"
rss: "/atom.xml"
lang: "ru"

# Plugins
plugins:
  - "jekyll-paginate"

# Exceptions
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "LICENSE.md"
  - "README.md"
