# Permalinks
permalink: /blog/:title/

# Time Zone
timezone: Europe/Moscow

# Catalogs
include:
    - _pages

# Parsers
highlighter: rouge
markdown: kramdown

# Markdown
kramdown:
    input: GFM
    hard_wrap: false
    syntax_highlighter: rouge

# SASS/SCSS
sass:
    sass_dir: _scss
    sourcemap: never
    style: :compressed

# Compress HTML
compress_html:
    blanklines: false
    clippings: all
    comments: ["<!-- ", " -->"]
    endings: all
    profile: false
    startings: []

# Website address
url: "https://valentineus.github.io"
baseurl: ""

# Site description
title: Valentin Popov's Technology Blog
description: Tech insights and coding best practices from an OpenSource enthusiast and ethical hacker.
email: valentin@popov.link
rss: /feed.xml
lang: ru

# Plugins
plugins:
    - jekyll-feed
    - jekyll-sitemap

# Exceptions
exclude:
    - .*
    - Gemfile
    - Gemfile.lock
    - LICENSE.txt
    - README.md
