# Permalinks
permalink: /:year-:month-:day/:title

# Setup
title:    "Blog"
paginate: 5
baseurl:  ""
url:      "https://valentineus.github.io"

# Assets
sass:
  sass_dir: "_sass"
  style:    ":compressed"

# Build settings
markdown: kramdown

# About
author:
  name:  "Valentin Popov"
  url:   "https://valentineus.link"
  email: "info@valentineus.link"

# Custom vars
version: 3.4.1
github:
  repo: "https://github.com/valentineus/valentineus.github.io"

# Gems
plugins:
  - "jekyll-paginate"
