# Permalinks
permalink: /:year-:month-:day/:title

# Catalogs
include: [ "_pages" ]

# Dependencies
highlighter: rouge
markdown: kramdown

# Compress HTML
compress_html:
  blanklines: false
  clippings: all
  comments: all
  endings: []
  profile: false
  startings: []

# Basic
baseurl: ""
url: "http://valentineus.link"
description: "Выжимка полезной информации из собственного опыта. Заметки, статьи и черновики."
title: "Blog"
rss: "/atom.xml"

# About
author:
  email: "info@valentineus.link"
  name: "Valentin Popov"
  url: "http://valentineus.link"

# References
links:
  github: "https://github.com/valentineus"
  twitter: "https://twitter.com/valyaha"

# Gems
plugins:
  - "jekyll-paginate"
