# Permalinks
permalink: '/:year-:month-:day/:title'

# Time Zone
timezone: 'Europe/Samara'

# Catalogs
include:
  - '_pages'

# Parsers
highlighter: rouge
markdown: kramdown

# Markdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# SASS/SCSS
sass:
  sass_dir: '_scss'
  style: ':compressed'

# AutoPrefixer
autoprefixer:
  browsers:
    - '> 1%'
    - 'last 10 versions'

# Compress HTML
compress_html:
  blanklines: false
  clippings: all
  comments: ['<!-- ', ' -->']
  endings: []
  profile: false
  startings: []

# Website address
url: 'https://valentineus.link'
baseurl: ''

# Site description
title: 'Personal blog'
description: 'Free developer and dreamer'
avatar: 'https://www.gravatar.com/avatar/989fb5288ac482414a6d13acc329cc38?s=148'
repos: 'https://github.com/valentineus/valentineus.github.io'
rss: '/atom.xml'
lang: 'ru'

# About the author
author:
  email: 'info@valentineus.link'
  name: 'Valentin Popov'
  url: 'https://valentineus.link'

# Plugins
plugins:
  - 'octopress-autoprefixer'

# Exceptions
exclude:
  - '.*'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'LICENSE.txt'
  - 'README.md'
