name: Deploy
on: [push, pull_request]

jobs:
  build:
    container: gitea/runner-images:ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: website
          path: dist/
          compression-level: 9

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: website
      - run: rsync --delete-after -a ./ /var/www/popov.link/
