name: RenovateBot
on:
  schedule:
    - cron: "@daily"

jobs:
  renovate:
    container: ghcr.io/renovatebot/renovate:40-full
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Renovate updates
        run: renovate
        env:
          RENOVATE_CONFIG_FILE: renovate.config.cjs
          RENOVATE_REPOSITORIES: ${{ gitea.repository }}
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
